/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiBlogIndexRouteImport } from './routes/api/blog.index'
import { Route as ApiBlogIdRouteImport } from './routes/api/blog.$id'
import { Route as ApiAdminBlogRouteImport } from './routes/api/admin.blog'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogIndexRoute = ApiBlogIndexRouteImport.update({
  id: '/api/blog/',
  path: '/api/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogIdRoute = ApiBlogIdRouteImport.update({
  id: '/api/blog/$id',
  path: '/api/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBlogRoute = ApiAdminBlogRouteImport.update({
  id: '/api/admin/blog',
  path: '/api/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/projects': typeof ApiProjectsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/admin/blog': typeof ApiAdminBlogRoute
  '/api/blog/$id': typeof ApiBlogIdRoute
  '/api/blog/': typeof ApiBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/projects': typeof ApiProjectsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/admin/blog': typeof ApiAdminBlogRoute
  '/api/blog/$id': typeof ApiBlogIdRoute
  '/api/blog': typeof ApiBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/projects': typeof ApiProjectsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/admin/blog': typeof ApiAdminBlogRoute
  '/api/blog/$id': typeof ApiBlogIdRoute
  '/api/blog/': typeof ApiBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/certifications'
    | '/contact'
    | '/experience'
    | '/projects'
    | '/sitemap.xml'
    | '/skills'
    | '/api/contact'
    | '/api/projects'
    | '/blog/$slug'
    | '/api/admin/blog'
    | '/api/blog/$id'
    | '/api/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blog'
    | '/certifications'
    | '/contact'
    | '/experience'
    | '/projects'
    | '/sitemap.xml'
    | '/skills'
    | '/api/contact'
    | '/api/projects'
    | '/blog/$slug'
    | '/api/admin/blog'
    | '/api/blog/$id'
    | '/api/blog'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/certifications'
    | '/contact'
    | '/experience'
    | '/projects'
    | '/sitemap.xml'
    | '/skills'
    | '/api/contact'
    | '/api/projects'
    | '/blog/$slug'
    | '/api/admin/blog'
    | '/api/blog/$id'
    | '/api/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRouteWithChildren
  CertificationsRoute: typeof CertificationsRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
  ProjectsRoute: typeof ProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkillsRoute: typeof SkillsRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiAdminBlogRoute: typeof ApiAdminBlogRoute
  ApiBlogIdRoute: typeof ApiBlogIdRoute
  ApiBlogIndexRoute: typeof ApiBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/': {
      id: '/api/blog/'
      path: '/api/blog'
      fullPath: '/api/blog/'
      preLoaderRoute: typeof ApiBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/$id': {
      id: '/api/blog/$id'
      path: '/api/blog/$id'
      fullPath: '/api/blog/$id'
      preLoaderRoute: typeof ApiBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/blog': {
      id: '/api/admin/blog'
      path: '/api/admin/blog'
      fullPath: '/api/admin/blog'
      preLoaderRoute: typeof ApiAdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRouteWithChildren,
  CertificationsRoute: CertificationsRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
  ProjectsRoute: ProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkillsRoute: SkillsRoute,
  ApiContactRoute: ApiContactRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiAdminBlogRoute: ApiAdminBlogRoute,
  ApiBlogIdRoute: ApiBlogIdRoute,
  ApiBlogIndexRoute: ApiBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
